# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dfIJj5apETLvW0XWQtV36aiaHLohQwz6
"""

#!pip install streamlit

#!pip install pulp

# Commented out IPython magic to ensure Python compatibility.
# %%writefile solver.py
# import pulp
# 
# def build_and_solve(num_employees, D, T, C_it, W_dt, P_idt, maxShift_i):
#     # Model
#     model = pulp.LpProblem("Scheduling", pulp.LpMinimize)
# 
#     # Decision variables
#     x_main = pulp.LpVariable.dicts("main", (range(1,num_employees+1), D, T), cat="Binary")
#     x_backup = pulp.LpVariable.dicts("backup", (range(1,num_employees+1), D, T), cat="Binary")
# 
#     # Objective: minimize total cost
#     model += pulp.lpSum(C_it[(i,t)] * x_main[i][d][t] for i in range(1,num_employees+1) for d in D for t in T)
# 
#     # Constraints
#     for d in D:
#         for t in T:
#             # ต้องมีพนักงานหลักครบตามต้องการ
#             model += pulp.lpSum(x_main[i][d][t] for i in range(1,num_employees+1)) == W_dt[(d,t)]
#             # ห้ามเลือกพนักงานที่ไม่ว่าง
#             for i in range(1,num_employees+1):
#                 model += x_main[i][d][t] <= P_idt[(i,d,t)]
# 
#     # จำกัดจำนวนกะสูงสุดต่อคน
#     for i in range(1,num_employees+1):
#         model += pulp.lpSum(x_main[i][d][t] for d in D for t in T) <= maxShift_i[i]
# 
#     # Solve
#     model.solve(pulp.PULP_CBC_CMD(msg=False))
# 
#     # Extract results
#     main_schedule = {(d,t): [] for d in D for t in T}
#     for d in D:
#         for t in T:
#             for i in range(1,num_employees+1):
#                 if pulp.value(x_main[i][d][t]) == 1:
#                     main_schedule[(d,t)].append(i)
# 
#     main_count = {i: sum(pulp.value(x_main[i][d][t]) for d in D for t in T) for i in range(1,num_employees+1)}
#     total_cost = {i: main_count[i]*320 for i in range(1,num_employees+1)}
# 
#     result = {
#         "status": pulp.LpStatus[model.status],
#         "main": main_schedule,
#         "main_count": main_count,
#         "total_cost": total_cost,
#         "backup": {(d,t): [] for d in D for t in T}  # ยังไม่ได้ใส่ backup logic
#     }
# 
#     return result
#

# app.py
import streamlit as st
import pandas as pd
import numpy as np
from M2T1P8 import build_and_solve
from io import StringIO

st.set_page_config(page_title="Scheduler", layout="wide", initial_sidebar_state="expanded")
st.markdown("<h1 style='color:#0b5f8a'>ระบบจัดตารางพนักงานพาร์ทไทม์</h1>", unsafe_allow_html=True)
st.write("ธีม: ฟ้า / เทา / ขาว — กรอกข้อมูลแล้วกด Solve")

# --- Inputs ---
with st.sidebar:
    st.header("ตั้งค่าพื้นฐาน")
    names_input = st.text_area("1) ใส่รายชื่อพนักงาน (comma-separated)",
                               value=",".join([f"Emp{i}" for i in range(1,17)]))
    month = st.selectbox("2) เลือกเดือน", ["January","February","March","April","May","June","July","Aug","Sep","Oct","Nov","Dec"])
    mode = st.selectbox("3) เลือกการจัด", ["เรียง (deterministic)","สุ่ม (random)"])
    st.markdown("---")
    st.header("4) ตัวเลือกความต้องการต่อกะ")
    w1 = st.number_input("กะ 1 ต้องการ (11:00-15:00)", min_value=0, value=1)
    w2 = st.number_input("กะ 2 ต้องการ (15:00-17:00)", min_value=0, value=2)
    w3 = st.number_input("กะ 3 ต้องการ (17:00-19:00)", min_value=0, value=3)
    w4 = st.number_input("กะ 4 ต้องการ (19:00-21:00)", min_value=0, value=2)
    st.markdown("---")
    st.header("5) availability (สองทางเลือก)")
    st.write("A) วาง matrix (16 rows x 12 cols) หรือ B) อัปโหลด CSV (16x12)")
    avail_text = st.text_area("วาง matrix (แต่ละแถวเป็น '0/1' คั่นด้วย space หรือ comma)", height=120)
    avail_file = st.file_uploader("หรืออัปโหลด CSV availability (16 rows × 12 cols)", type=["csv"])

    st.markdown("---")
    st.header("6) ข้อจำกัดต่อคน")
    max_shift = st.number_input("Max shifts per employee (ตัวจริง)", min_value=1, max_value=12, value=3)
    st.markdown("---")
    st.button("Apply & Solve", key="solve")

# parse names
names = [n.strip() for n in names_input.split(",") if n.strip()]
num_employees = len(names)
st.write(f"จำนวนพนักงานที่ใส่: {num_employees}")

# build availability matrix P_idt: shape (num_employees, 6 days, 4 shifts) -> 12 slots per employee
# We'll accept 12 columns ordered: D1-T1,T2,T3,T4 ; D2-T1.. etc -> total 6*4 =12
if avail_file is not None:
    df_av = pd.read_csv(avail_file, header=None)
    st.write("Uploaded availability (first rows):")
    st.dataframe(df_av.head())
    avail = df_av.values
else:
    avail = None
    if avail_text:
        rows = [r.strip() for r in avail_text.strip().splitlines() if r.strip()]
        parsed = []
        for r in rows:
            parts = [p for p in r.replace(",", " ").split() if p!='']
            parsed.append([int(x) for x in parts])
        avail = np.array(parsed)

# default fallback: if no availability given, set all available
if avail is None or avail.size == 0:
    avail = np.ones((num_employees, 12), dtype=int)

# validate shape
if avail.shape[0] != num_employees or avail.shape[1] != 12:
    st.error(f"Availability shape mismatch: expected ({num_employees},12) but got {avail.shape}. Please fix.")
else:
    # build P_idt dict
    I = list(range(1, num_employees+1))
    D = range(1,7)
    T = range(1,5)   # 1..4 กะต่อวัน

P_idt = {}
for idx, i in enumerate(I):
    row = avail[idx]
    if len(row) != 24:
        st.error(f"แต่ละแถวต้องมี 24 ค่า (6 วัน × 4 กะ) แต่พบ {len(row)} ค่า")
        continue
    k = 0
    for d in D:
        for t in T:
            P_idt[(i,d,t)] = int(row[k])
            k += 1

    # cost and W_dt
    C_it = {(i,t): 320 if t==1 else 160 for i in I for t in T}
    W_dt = {(d,t): int([w1,w2,w3,w4][t-1]) for d in D for t in T}
    maxShift_i = {i: int(max_shift) for i in I}

    if st.button("Solve now"):
        with st.spinner("Solving..."):
            res = build_and_solve(num_employees, D, T, C_it, W_dt, P_idt, maxShift_i)

        st.success(f"Status: {res['status']}")
        # show main schedule table
        st.subheader("ตารางตัวจริง (Main)")
        rows = []
        for d in D:
            for t in T:
                emp_list = res["main"][(d,t)]
                rows.append({"day":d,"shift":t,"names":", ".join([names[i-1] for i in emp_list])})
        df_main = pd.DataFrame(rows)
        st.dataframe(df_main)

        st.subheader("ตารางสำรอง (Backup)")
        rowsb=[]
        for d in D:
            for t in T:
                emp_list = res["backup"][(d,t)]
                rowsb.append({"day":d,"shift":t,"names":", ".join([names[i-1] for i in emp_list])})
        st.dataframe(pd.DataFrame(rowsb))

        st.subheader("สรุปจำนวนกะต่อคน (ตัวจริง)")
        summary = [{"name": names[i-1], "main_shifts": res["main_count"][i], "cost": res["total_cost"][i]} for i in I]
        st.dataframe(pd.DataFrame(summary))

        st.markdown("---")
        st.subheader("จำลอง: ถ้ามีพนักงานขาด ให้เลือกสำรองมาแทน")
        absent_emp_index = st.selectbox("เลือกพนักงานที่ขาด (index)", I)
        absent_day = st.selectbox("day (1=Sun..6=Fri)", D)
        absent_shift = st.selectbox("shift (1..4)", T)
        if st.button("Find replacement"):
            candidates = [i for i in I if res["backup"][(absent_day,absent_shift)] and i in res["backup"][(absent_day,absent_shift)]]
            if not candidates:
                st.warning("ไม่มีสำรองพร้อมใน slot นี้")
            else:
                # pick lowest cost then least main shifts
                chosen = min(candidates, key=lambda i: (res["total_cost"][i], res["main_count"][i]))
                st.success(f"แนะนำสำรอง: {names[chosen-1]} (index {chosen})")
